### ISSUE TITLE
Tool version, aka dwVersion / XACT_CONTENT_VERSION, is not numeric

### ISSUE THREAD

**Issue by Evgen2194** [astrogab42/XwbAudioReplacer#11] opened 2024-01-14 14:46 UTC
I get this error when I try to repack

ERROR   Tool version, aka dwVersion / XACT_CONTENT_VERSION, is not numeric. The file SFXNew.xwb could be corrupted.
ERROR   Fatal Error! Exiting...

user files are smaller than the original counterpart.

I even tried to unpack the xwb file and pack it right back, but I still get the same error

![image](https://github.com/astrogab42/XwbAudioReplacer/assets/44700171/d193641e-5335-446e-b34e-888f2f5999e0)

**Comment by DeiranZ** [comment] 2024-01-23 16:43
I'm having the exact same issue.
I've commented out the "exit" commands for this check, but then it just says:
`Tool version, aka dwVersion / XACT_CONTENT_VERSION, and File format, aka dwHeaderVersion, are not recognised.`
`Do you want to continue? (Y/N)`
After I continue, nothing happens.

**Comment by astrogab42** [comment] 2024-01-23 17:50
Hello!! We’re sorry for that, we didn’t tested the SFX file. We’ll try to do our best to fix it.
We’ll share an update as soon as possible!
-astrogab

**Comment by Evgen2194** [comment] 2024-01-23 18:12
Not only SFX file, the Speech file also has the same error. I just tried to pack the changed files in Speech, but I unpacked SFX for testing and tried to pack it back without changes to check that the error was not due to the changed files.
Thank you!

**Comment by DeiranZ** [comment] 2024-01-23 18:42
Thanks for the response @astrogab42, I've also had the exact same issue using the Speech.xwb file.
I'm using Windows 10 x64, and have the Steam edition of the game.

**Comment by Steve2811** [comment] 2024-01-23 18:53
Thanks for reporting the problem! The files are probably more different than we imagined. I think the problem is due to the fact that the file headers are different. Our script tries to read the version number from the header but there is other data at that position. We will analyze the problem and try to solve it as soon as possible!

**Comment by astrogab42** [comment] 2024-05-29 14:57
Hello everybody, the fix has been tested and released. Please, check on your sides and let us now. Thank you!

**Closed by astrogab42** 2024-05-29 14:57 UTC
